import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  images: [], // List of image-folder relations.
  folders: [], // List of user-created folders.
};

// A slice is built with name, initialState, and reducers.
const imageSlice = createSlice({
  initialState,
  name: "image",
  // reducers !! 
  reducers: {
    setImages: (state, action) => {
      state.images = action.payload;
    },
    setFolders: (state, action) => {
      state.folders = action.payload;
    },
    // this reducer can both assign an image to a folder. 
    assignImageToFolder: (state, action) => {
      const { uri, folderId } = action.payload;
      // Update the existing image entry if we already know this URI.
      const existing = state.images.find((image) => image.uri === uri);
      if (existing) {
        existing.folderId = folderId;
      } else {
        // Otherwise, create a new image entry.
        state.images.push({ uri, folderId });
      }
    },
    // this reducer can be used to unassign an image from any folder by setting its folderId to null. 
    removeImageFromFolder: (state, action) => {
      const { uri } = action.payload;
      const existing = state.images.find((image) => image.uri === uri);
      if (existing) {
        existing.folderId = null;
      }
    },
  },
});

// Actions generated from reducers above.
export const {
  setImages,
  setFolders,
  assignImageToFolder,
  removeImageFromFolder,
} = imageSlice.actions;

// Selectors to read this slice from the global Redux state.

export const selectImages = (state) => state.image.images;
export const selectFolders = (state) => state.image.folders;

// Reducer generated by createSlice.
export default imageSlice.reducer;
